name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        include:
        - python: '2.7'
        - python: '3.5'
          os: ubuntu-20.04
        - python: '3.6'
          os: ubuntu-20.04
        - python: '3.7'
          os: ubuntu-20.04
        - python: '3.8'
          os: ubuntu-20.04
        - python: '3.9'
          os: ubuntu-20.04
        - python: '3.10'
          os: ubuntu-22.04
        - python: '3.11'
          os: ubuntu-22.04
        - python: '3.12-dev'
          os: ubuntu-22.04
          wheel: '>= 0.38'
    runs-on: ${{matrix.os || 'ubuntu-latest'}}
    container: ${{ ((matrix.python == '2.7') && 'python:2.7') || null }}
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    - name: set up Python ${{matrix.python}}
      if: matrix.python != '2.7'
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.python}}
    - name: set up pip
      if: env.pythonLocation
      run: |
        sed -i -e 's/ sys.exit(.*)/ raise/' ${{env.pythonLocation}}/lib/python*/site-packages/pip/_internal/utils/setuptools_build.py
        python -m pip list
    - name: install setuptools (if distutils is missing)
      if: env.pythonLocation
      run: |
        if ! [ -d ${{env.pythonLocation}}/lib/python*/distutils/ ]; then
          python -m pip install setuptools
        fi
    - name: install wheel
      run: |
        python -m pip install "wheel${{matrix.wheel || '<0.38'}}"
    - name: run tests
      run: |
        make test
    - name: run pydiatra
      run: |
        python -m pip install pydiatra
        python -m pydiatra -v .
    - name: run pyflakes
      run: |
        python -m pip install pyflakes
        python -m pyflakes .
    - name: run pylint
      run: |
        python -m pip install pylint
        private/run-pylint
    - name: check docs
      run: |
        dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
        python -m pip install docutils pygments
        private/check-rst
    - name: install
      run: |
        python setup.py install
    - name: check whether the module was installed correctly
      run: |
        cd /
        python -c 'import distutils644'

# vim:ts=2 sts=2 sw=2 et
